"""add progress update history

Revision ID: d3d3a421a8a8
Revises: e398e9a99703
Create Date: 2026-09-18 04:35:46.213446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3d3a421a8a8'
down_revision = 'e398e9a99703'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('progress_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phase_id', sa.Integer(), nullable=False),
    sa.Column('completion_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['phase_id'], ['phases.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('progress_updates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_progress_updates_phase_id'), ['phase_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progress_updates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_progress_updates_phase_id'))

    op.drop_table('progress_updates')
    # ### end Alembic commands ###
